name: Test
on:
  workflow_dispatch:
  pull_request:
    paths: ["action.yml", ".github/workflows/test.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        with:
          app-id: ${{ secrets.TESTING_APP_ID }}
          app-private-key: ${{ secrets.TESTING_APP_PRIVATE_KEY }}
          repositories: ${{ vars.TESTING_REPOSITORY }}

      - name: Verify
        env:
          REPOSITORY: ${{ vars.TESTING_REPOSITORY }}
          INITIAL_COMMIT: ${{ vars.TESTING_REPOSITORY_INITIAL_COMMIT }}
          GH_TOKEN: ${{ steps.exercise.outputs.token }}
        run: |
          set -x
          result="$(gh api \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${GITHUB_REPOSITORY_OWNER}/${REPOSITORY}/commits/${INITIAL_COMMIT}" \
            | jq -r '.commit.message')"
          test "$?" = "0"
          test "${result}" = "Initial commit"

      - name: Teardown
        if: ${{ always() }}
        uses: tmknom/revoke-github-token-action@aef39d8fd7bfb1baeab3a021fe7a78362a59501f # v0.1.1
        with:
          token: ${{ steps.exercise.outputs.token }}

  test-multi-repo:
    name: Test multiple repositories
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        with:
          app-id: ${{ secrets.TESTING_APP_ID }}
          app-private-key: ${{ secrets.TESTING_APP_PRIVATE_KEY }}
          repositories: ${{ vars.TESTING_REPOSITORY }} ${{ vars.TESTING_ADDITIONAL_REPOSITORY }}

      - name: Verify
        env:
          REPOSITORY: ${{ vars.TESTING_REPOSITORY }}
          INITIAL_COMMIT: ${{ vars.TESTING_REPOSITORY_INITIAL_COMMIT }}
          ADDITIONAL_REPOSITORY: ${{ vars.TESTING_ADDITIONAL_REPOSITORY }}
          ADDITIONAL_INITIAL_COMMIT: ${{ vars.TESTING_ADDITIONAL_REPOSITORY_INITIAL_COMMIT }}
          GH_TOKEN: ${{ steps.exercise.outputs.token }}
        run: |
          set -x
          result1="$(gh api \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${GITHUB_REPOSITORY_OWNER}/${REPOSITORY}/commits/${INITIAL_COMMIT}" \
            | jq -r '.commit.message')"
          test "$?" = "0"

          result2="$(gh api \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${GITHUB_REPOSITORY_OWNER}/${ADDITIONAL_REPOSITORY}/commits/${ADDITIONAL_INITIAL_COMMIT}" \
            | jq -r '.commit.message')"
          test "$?" = "0"

          test "${result1}" = "${result2}"

      - name: Teardown
        if: ${{ always() }}
        uses: tmknom/revoke-github-token-action@aef39d8fd7bfb1baeab3a021fe7a78362a59501f # v0.1.1
        with:
          token: ${{ steps.exercise.outputs.token }}

  test-key-file:
    name: Test app-private-key-file input
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Setup
        id: setup
        env:
          APP_PRIVATE_KEY: ${{ secrets.TESTING_APP_PRIVATE_KEY }}
        run: |
          set -x
          key_file="${RUNNER_TEMP}/app_private.key"
          printenv APP_PRIVATE_KEY > "${key_file}"
          echo "file=${key_file}" >> "${GITHUB_OUTPUT}"

      - name: Exercise
        id: exercise
        uses: ./
        with:
          app-id: ${{ secrets.TESTING_APP_ID }}
          app-private-key-file: ${{ steps.setup.outputs.file }}
          repositories: ${{ vars.TESTING_REPOSITORY }}

      - name: Verify
        env:
          REPOSITORY: ${{ vars.TESTING_REPOSITORY }}
          INITIAL_COMMIT: ${{ vars.TESTING_REPOSITORY_INITIAL_COMMIT }}
          GH_TOKEN: ${{ steps.exercise.outputs.token }}
        run: |
          set -x
          result="$(gh api \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${GITHUB_REPOSITORY_OWNER}/${REPOSITORY}/commits/${INITIAL_COMMIT}" \
            | jq -r '.commit.message')"
          test "$?" = "0"
          test "${result}" = "Initial commit"

      - name: Teardown
        if: ${{ always() }}
        uses: tmknom/revoke-github-token-action@aef39d8fd7bfb1baeab3a021fe7a78362a59501f # v0.1.1
        with:
          token: ${{ steps.exercise.outputs.token }}
